### ISSUE TITLE
setup_venv.sh fails on macos sed

### ISSUE THREAD

**Issue by dekobon** [nginxinc/kic-reference-architectures#168]
**Describe the bug**
When running `setup_venv.sh` on MacOS, the script fails:
```
Downloading Pulumi CLI into virtual environment
sed: illegal option -- r
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
```

**Expected behavior**
Sed should be invoked with the posix compatible flag `-E` instead of `-r` which is specific to GNU sed.

**Comment by qdzlug** [comment]
Will close with #167
