### ISSUE TITLE
Add support for not building the ingress controller and using the default OSS version

### ISSUE THREAD

**Issue by dekobon** [nginxinc/kic-reference-architectures#18]
Currently, the reference architecture is designed such that you have to build the ingress controller from scratch. With this change, you can now opt to use the default ingress controller as installed from helm without building.

**Comment by dekobon** [comment]
Fixed in 70db8b82db3b81b5f7edfa0c9e464a64aa26fde4

**Comment by qdzlug** [comment]
Closing out, fixed as noted above. Additionally, the ingress-repo-only project uses a JWT to pull plus or oss depending on the user choices. This will also be refactored in #81
