### ISSUE TITLE
fail to deploy prometheus

### ISSUE THREAD

**Issue by xp2014** [nginxinc/kic-reference-architectures#204]
**Describe the bug**
Fail to deploy prometheus with ./bin/start.sh.

**To Reproduce**
1. Deploy a stack with ./bin/start.sh
2. View logs on terminal
3. See error

error: Program failed with an unhandled exception:

**Your environment**
* Version of the repo -v1.1.1
* Version of infrastructure tooling (Pulumi)
* Version of executing environment (Python)
* OS and distribution: ubuntu 20
* Details about containerization or virtualization environment: Microk8s

**Additional context**
[fail to deploy prometheus.log](https://github.com/nginxinc/kic-reference-architectures/files/9917365/fail.to.deploy.prometheus.log)

**Comment by qdzlug** [comment]
Hi @xp2014 ,

Can you let me know what version of microk8s you are running? we have known issues with 1.24 https://github.com/nginxinc/kic-reference-architectures/issues/182 

Jay

**Comment by xp2014** [comment]
@qdzlug 

1.23/stable:           v1.23.9

Thanks,
XP

**Comment by xp2014** [comment]
> Found the issue; when we refactored to use the python based startup script and the _secrets_ namespace we missed ensuring that the admin password for Grafana was added to the config. This wasn't impacting the automated testing since that builds the config automatically.
> 
> Working on a patch for the repo, but short term, you can get around this by adding the value manually
> 
> ```
> pulumi config set prometheus:adminpass "${MARA_PASSWORD}" --secret -C pulumi/python/kubernetes/secrets -s "${STACKNAME}"
> ```
> 
> where you substitute your values for the two variables.

Thanks!
